# Site wide configuration
title: "Learning Blog"
description: "My computer code learning blog."
baseurl: "/blog"


# Jekyll configuration
#repository: https://github.com/amybaldwindev/blog


# Site owner
owner:
  name: "Amy Baldwin"
  email:
  twitter: 
  google:
  bio: 
  avatar: 
  disqus-shortname: "amybaldwindev"
#Google services
google_analytics: UA-104493899-1